### ISSUE TITLE
adopt strategy blanks ancestry column instead of nillify

### ISSUE THREAD

**Issue by Skulli** [stefankroes/ancestry#225]
Was wondering why i had some entries in the database with an empty string stored in the ancestry column, which was causing issues with queries like _roots_.

During my test i noticed, that when you delete the root, the children will get the empty string instead of nil stored in the ancestry column. (orphan_strategy is adopt)

**Comment by kdelvare** [comment]
Same problem here. orphan_strategy: :adopt, I delete a root, and its children get ancestry "" instead of nil, which causes validation errors afterwards. ActiveRecord::RecordInvalid: Validation failed: Ancestry is invalid

**Comment by maartenparmentier** [comment]
same here

**Comment by kbrock** [comment]
I noticed [test](https://github.com/stefankroes/ancestry/blob/master/test/concerns/orphan_strategies_test.rb#L86)

Is this a problem with the published gem, or on master?
Is there a test we can add to ensure this is fixed?

**Comment by Skulli** [comment]
still having the problem from time to time

ancestry should either guarantee nil is stored or it should handle empty string and nil the same way.

**Comment by jimmybaker** [comment]
This is no longer an issue in the latest release. You can probably close this.

**Comment by kbrock** [comment]
@jimmybaker thank you
